#!/bin/bash

TARGET_DIR="$HOME/Desktop/paper/homepage/gallery"
cd "$TARGET_DIR" || { echo "경로를 찾을 수 없습니다: $TARGET_DIR"; exit 1; }

OUTPUT_DIR="output"
rm -f "$OUTPUT_DIR"/*.jpg "$OUTPUT_DIR"/*.jpeg "$OUTPUT_DIR"/*.png "$OUTPUT_DIR"/order.js 2>/dev/null
mkdir -p "$OUTPUT_DIR"

echo "날짜순 정렬 후 이미지 변환 및 썸네일 생성을 시작합니다..."

TMPFILE=$(mktemp)

shopt -s nullglob nocaseglob
for file in *.{heic,jpg,jpeg,png}; do
    DATE=$(mdls -name kMDItemContentCreationDate "$file" 2>/dev/null \
        | awk '{print $3, $4}' | head -1)
    if [ -z "$DATE" ] || [ "$DATE" = "null" ]; then
        DATE=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S" "$file")
    fi
    echo "$DATE	$file" >> "$TMPFILE"
done
shopt -u nullglob nocaseglob

COUNTER=1
COLOR_TMPFILE=$(mktemp)

while IFS='	' read -r DATE FILE; do
    LARGE_NAME="${OUTPUT_DIR}/Photo ${COUNTER}.jpg"
    THUMB_NAME="${OUTPUT_DIR}/thumb_Photo ${COUNTER}.jpg"

    echo "[$COUNTER] '$FILE' ($DATE)"

    sips -s format jpeg -s formatOptions 80 -Z 1920 "$FILE" --out "$LARGE_NAME" > /dev/null 2>&1
    sips -s format jpeg -s formatOptions 70 -Z 400  "$FILE" --out "$THUMB_NAME" > /dev/null 2>&1

    # dominant hue: 1x1 평균 색상 추출
    sips -z 1 1 "$LARGE_NAME" --out /tmp/_avg_color.bmp -s format bmp > /dev/null 2>&1
    HUE=$(python3 - <<'EOF'
import sys
try:
    with open('/tmp/_avg_color.bmp', 'rb') as f:
        f.seek(54)
        data = f.read(3)
    b, g, r = data[0]/255, data[1]/255, data[2]/255
    mx, mn = max(r,g,b), min(r,g,b)
    s = (mx-mn)/(2-mx-mn) if (mx+mn)/2 > 0.5 else (mx-mn)/(mx+mn+1e-9)
    if mx == mn or s < 0.08:
        # 무채색은 hue 999로 뒤로 보냄
        print(999)
    else:
        d = mx - mn
        if mx == r:   h = (g-b)/d + (6 if g<b else 0)
        elif mx == g: h = (b-r)/d + 2
        else:         h = (r-g)/d + 4
        print(round(h*60, 1))
except:
    print(999)
EOF
)
    echo "$HUE $COUNTER" >> "$COLOR_TMPFILE"

    # landscape 여부 기록
    W=$(sips -g pixelWidth  "$LARGE_NAME" 2>/dev/null | awk '/pixelWidth/{print $2}')
    H=$(sips -g pixelHeight "$LARGE_NAME" 2>/dev/null | awk '/pixelHeight/{print $2}')
    if [ -n "$W" ] && [ -n "$H" ] && [ "$W" -gt "$H" ] 2>/dev/null; then
        echo "$COUNTER" >> "$OUTPUT_DIR/_wide.tmp"
    fi

    ((COUNTER++))
done < <(sort -r "$TMPFILE")

rm -f "$TMPFILE"
TOTAL=$((COUNTER-1))

# hue 기준 정렬해서 order.js 생성
ORDER=$(sort -n "$COLOR_TMPFILE" | awk '{printf "%s,", $2}' | sed 's/,$//')
rm -f "$COLOR_TMPFILE"

WIDE_LIST=$(sort -n "$OUTPUT_DIR/_wide.tmp" 2>/dev/null | awk '{printf "%s,", $1}' | sed 's/,$//')
rm -f "$OUTPUT_DIR/_wide.tmp"

cat > "$OUTPUT_DIR/order.js" <<EOF
// auto-generated by thumbnail.sh — do not edit
const GALLERY_TOTAL = $TOTAL;
const GALLERY_COLOR_ORDER = [$ORDER];
const GALLERY_WIDE = new Set([$WIDE_LIST]);
EOF

echo "완료! 총 ${TOTAL}장 생성, order.js 저장됨."
